import type { SecurityCheck } from '@xdigitex/scanner-core';
import { finding } from './helpers';

type Candidate={path:string;title:string;category:string;severity:'HIGH'|'MEDIUM'|'LOW'|'INFORMATIONAL';method?:'GET'|'HEAD';signature?:RegExp;description:string;impact:string;remediation:string};

const candidates:Candidate[]=[
  {path:'/.env',title:'Environment configuration file exposed',category:'Secret Exposure',severity:'HIGH',signature:/(?:APP_KEY|DB_(?:HOST|DATABASE|USERNAME|PASSWORD)|DATABASE_URL|MAIL_(?:HOST|USERNAME|PASSWORD)|API[_-]?KEY|SECRET|TOKEN)\s*=/i,description:'A production environment/configuration file is publicly reachable.',impact:'Environment files commonly contain database, mail, API or application secrets that can enable unauthorized access.',remediation:'Remove the file from the web root, deny dotfile access at the web server, rotate exposed credentials and review deployment packaging.'},
  {path:'/.env.local',title:'Local environment file exposed',category:'Secret Exposure',severity:'HIGH',signature:/(?:DB_|DATABASE_URL|API[_-]?KEY|SECRET|TOKEN|PASSWORD)\s*=/i,description:'A local environment file is publicly reachable.',impact:'The file may disclose credentials, service endpoints or application secrets.',remediation:'Remove environment files from public document roots and rotate any exposed values.'},
  {path:'/.env.production',title:'Production environment file exposed',category:'Secret Exposure',severity:'HIGH',signature:/(?:DB_|DATABASE_URL|API[_-]?KEY|SECRET|TOKEN|PASSWORD)\s*=/i,description:'A production environment file is publicly reachable.',impact:'Production credentials or service configuration may be disclosed.',remediation:'Remove it from public hosting, deny dotfile access and rotate exposed secrets.'},
  {path:'/.git/HEAD',title:'Git repository metadata exposed',category:'Source Exposure',severity:'MEDIUM',signature:/^ref:\s+refs\//m,description:'The Git metadata endpoint is publicly readable.',impact:'An exposed .git directory can allow reconstruction of source history and reveal sensitive implementation details or secrets committed previously.',remediation:'Block access to .git and other VCS metadata at the web server and remove repository metadata from deployment artifacts.'},
  {path:'/composer.json',title:'Composer manifest publicly exposed',category:'Technology Disclosure',severity:'INFORMATIONAL',signature:/"(?:require|autoload|name)"\s*:/i,description:'The Composer package manifest is publicly readable.',impact:'Dependency and framework details can improve attacker reconnaissance.',remediation:'Expose dependency manifests only when operationally required.'},
  {path:'/composer.lock',title:'Composer lock file publicly exposed',category:'Technology Disclosure',severity:'LOW',signature:/"packages"\s*:\s*\[/i,description:'The Composer lock file is publicly readable.',impact:'Exact dependency versions can help identify known-vulnerable components.',remediation:'Keep build/dependency lock files outside the public document root.'},
  {path:'/package.json',title:'Node package manifest publicly exposed',category:'Technology Disclosure',severity:'INFORMATIONAL',signature:/"(?:dependencies|devDependencies|scripts)"\s*:/i,description:'A package manifest is publicly readable.',impact:'Dependency and build information can increase application fingerprinting accuracy.',remediation:'Do not publish development manifests unless intentionally required.'},
  {path:'/phpinfo.php',title:'PHP information page exposed',category:'Information Disclosure',severity:'MEDIUM',signature:/PHP Version|phpinfo\(\)/i,description:'A PHP information page appears publicly accessible.',impact:'phpinfo output can disclose paths, extensions, environment details and server configuration useful for follow-on attacks.',remediation:'Remove phpinfo/debug pages from production and restrict diagnostics to authenticated administrative channels.'},
  {path:'/info.php',title:'PHP information page exposed',category:'Information Disclosure',severity:'MEDIUM',signature:/PHP Version|phpinfo\(\)/i,description:'A PHP information page appears publicly accessible.',impact:'Diagnostic output can reveal sensitive platform configuration and filesystem details.',remediation:'Remove public diagnostic pages from production.'},
  {path:'/server-status',title:'Web server status page exposed',category:'Information Disclosure',severity:'MEDIUM',signature:/Apache Server Status|Server Version|Current Time/i,description:'A server status page is publicly reachable.',impact:'Runtime server information and active request details can disclose internal behavior.',remediation:'Disable public server-status access or restrict it to trusted administrative networks.'},
  {path:'/storage/logs/laravel.log',title:'Application log publicly exposed',category:'Information Disclosure',severity:'HIGH',signature:/(?:production\.(?:ERROR|WARNING)|Stack trace|SQLSTATE|local\.ERROR)/i,description:'An application log file is publicly reachable.',impact:'Logs may contain stack traces, internal paths, personal data, tokens or credentials.',remediation:'Move logs outside the web root, block direct access and review/rotate any sensitive values disclosed.'},
  {path:'/laravel.log',title:'Application log publicly exposed',category:'Information Disclosure',severity:'HIGH',signature:/(?:production\.(?:ERROR|WARNING)|Stack trace|SQLSTATE|local\.ERROR)/i,description:'An application log file is publicly reachable.',impact:'Logs can expose internal implementation details and sensitive request data.',remediation:'Keep logs outside public paths and restrict access.'},
  {path:'/error_log',title:'Web error log publicly exposed',category:'Information Disclosure',severity:'HIGH',signature:/(?:PHP (?:Warning|Fatal error|Notice)|Stack trace|SQLSTATE|\[[0-9]{2}-[A-Za-z]{3}-[0-9]{4})/i,description:'A web/application error log appears publicly readable.',impact:'Error logs can disclose filesystem paths, queries, secrets and user data.',remediation:'Block log-file access and store logs outside the public document root.'},
  {path:'/database.sql',title:'Database dump publicly exposed',category:'Data Exposure',severity:'HIGH',signature:/(?:CREATE TABLE|INSERT INTO|-- (?:MySQL|PostgreSQL)|pg_dump)/i,description:'A database export appears publicly readable.',impact:'A database dump can expose application data, account records, hashes, secrets and schema information.',remediation:'Immediately remove the dump from public hosting, review access logs, rotate exposed secrets and assess affected data.'},
  {path:'/db.sql',title:'Database dump publicly exposed',category:'Data Exposure',severity:'HIGH',signature:/(?:CREATE TABLE|INSERT INTO|-- (?:MySQL|PostgreSQL)|pg_dump)/i,description:'A database export appears publicly readable.',impact:'Database exports may expose highly sensitive application data.',remediation:'Remove public dumps immediately and perform credential/data exposure review.'},
  {path:'/dump.sql',title:'Database dump publicly exposed',category:'Data Exposure',severity:'HIGH',signature:/(?:CREATE TABLE|INSERT INTO|-- (?:MySQL|PostgreSQL)|pg_dump)/i,description:'A database export appears publicly readable.',impact:'Database exports may reveal user data, password hashes and application secrets.',remediation:'Remove the public dump and investigate possible exposure.'},
  {path:'/backup.zip',title:'Public backup archive detected',category:'Source / Backup Exposure',severity:'HIGH',method:'HEAD',description:'A common backup archive path responds as an accessible resource.',impact:'Backup archives can contain source code, configuration, database exports and credentials.',remediation:'Remove backup archives from public paths and store backups in access-controlled storage.'},
  {path:'/site.zip',title:'Public site archive detected',category:'Source / Backup Exposure',severity:'HIGH',method:'HEAD',description:'A common site archive path responds as an accessible resource.',impact:'Site archives may disclose source code and server-side configuration.',remediation:'Remove deployment archives from the public document root.'},
  {path:'/backup.tar.gz',title:'Public backup archive detected',category:'Source / Backup Exposure',severity:'HIGH',method:'HEAD',description:'A common compressed backup path responds as an accessible resource.',impact:'Backup archives can disclose source, secrets and application data.',remediation:'Move backups to private storage and deny public access.'}
];

function normalizeBody(body:string){return body.slice(0,2500).replace(/[a-f0-9]{16,}/gi,'#').replace(/\d{6,}/g,'#').replace(/\s+/g,' ').trim();}
function looksLikeArchive(r:{headers:Record<string,string>},path:string){const ct=(r.headers['content-type']||'').toLowerCase();const cd=(r.headers['content-disposition']||'').toLowerCase();return /(?:zip|gzip|x-tar|octet-stream)/.test(ct)||/attachment/.test(cd)||/\.(?:zip|tar\.gz)$/i.test(path);}

export const exposureCheck:SecurityCheck={id:'exposure.artifacts',name:'Exposed files, backups and diagnostics',category:'Exposure Discovery',async run(ctx){
  const out=[];const base=new URL(ctx.assetUrl);const miss=new URL(`/xdigitex-not-found-${Date.now().toString(36)}-a91f`,base).toString();
  const baseline=await ctx.http.request(miss).catch(()=>null);const baselineBody=baseline?normalizeBody(baseline.body):'';
  for(const c of candidates){
    if(await ctx.isCanceled())break;
    const url=new URL(c.path,base).toString();let r;
    try{r=await ctx.http.request(url,{method:c.method||'GET'});}catch{continue;}
    if(r.status<200||r.status>=300)continue;
    if(c.method==='HEAD'){
      if(!looksLikeArchive(r,c.path))continue;
    }else{
      const body=normalizeBody(r.body);if(!body)continue;
      if(baseline&&r.status===baseline.status&&baselineBody&&body===baselineBody)continue;
      if(c.signature&&!c.signature.test(r.body))continue;
    }
    out.push(finding({checkId:this.id,title:c.title,description:c.description,category:c.category,severity:c.severity,confidence:c.method==='HEAD'?'HIGH':'CONFIRMED',affectedUrl:r.url,method:c.method||'GET',impact:c.impact,remediation:c.remediation,evidence:[{...r.evidence,responseExcerpt:c.method==='HEAD'?'Resource responded successfully; body was not downloaded.':'Signature matched; response content omitted/redacted from this finding.'}]}));
  }
  return out;
}};
