import { redirect,notFound } from 'next/navigation';
import { currentUser,requireOrg } from '../../../lib/auth';
import { db } from '@xdigitex/database';

export default async function Page({params}:{params:Promise<{id:string}>}){
  if(!await currentUser()) redirect('/login');
  const {org,role}=await requireOrg();
  const {id}=await params;
  const a=await db.asset.findFirst({where:{id,organizationId:org.id},include:{verifications:{orderBy:{createdAt:'desc'},take:1},testIdentities:{orderBy:{createdAt:'asc'}},testResources:{orderBy:{createdAt:'asc'}}}});
  if(!a) notFound();
  const v=a.verifications[0];
  const canManage=['OWNER','ADMIN'].includes(role);
  return <div className="stack"><h1>{a.normalizedHost}</h1>
    {a.verifiedAt?<div className="card">Ownership verified. Safe scanning and controlled identity testing can be configured for this asset.</div>:<div className="card stack"><p>Choose a method. A fresh token is generated server-side.</p><form action={`/api/assets/${a.id}/verification`} method="post" className="row"><select name="method"><option value="DNS_TXT">DNS TXT</option><option value="FILE">Verification file</option><option value="META">HTML meta tag</option></select><button className="btn">Create verification</button></form>{v&&<><div><b>Current token</b><pre>{v.token}</pre></div><div className="muted">DNS: xdigitex-security-verification={v.token}<br/>File: /.well-known/xdigitex-security-verification.txt with token as body<br/>Meta: name="xdigitex-security-verification" content="{v.token}"</div><form action={`/api/assets/${a.id}/verification/check`} method="post"><button className="btn">Check verification</button></form></>}</div>}
    {a.verifiedAt&&<><div className="card stack"><h2>Controlled identities</h2><p className="muted">Identity records hold labels, roles, tenants and a deployment profile reference only. Reusable access material is not stored in the application database.</p>{a.testIdentities.length===0?<p className="muted">No identities configured.</p>:a.testIdentities.map(i=><div className="row" key={i.id}><b>{i.label}</b><span>{i.roleLabel}</span><span>{i.tenantLabel||'no tenant'}</span><span>{i.expectedSessionState}</span><code>{i.credentialRef}</code></div>)}{canManage&&<form action={`/api/assets/${a.id}/test-identities`} method="post" className="stack"><div className="row"><input name="label" placeholder="Identity label" required/><input name="roleLabel" placeholder="Role label" required/><input name="tenantLabel" placeholder="Tenant label"/></div><div className="row"><select name="authType"><option value="HEADERS">Header profile</option><option value="BEARER">Token profile</option><option value="COOKIE">Session profile</option></select><input name="credentialRef" placeholder="XD_TEST_PROFILE_MEMBER_A" required/><select name="expectedSessionState"><option value="ACTIVE">Expected active</option><option value="REVOKED">Expected revoked</option></select><button className="btn">Register identity</button></div></form>}</div>
    <div className="card stack"><h2>Authorization test resources</h2><p className="muted">Only owner-declared read-only URLs on this verified host are eligible. A harmless marker in test data can be supplied to improve evidence confidence.</p>{a.testResources.length===0?<p className="muted">No resources configured.</p>:a.testResources.map(r=><div key={r.id}><b>{r.label}</b> <code>{r.method} {r.url}</code> <span>{r.expectation}</span></div>)}{canManage&&a.testIdentities.length>0&&<form action={`/api/assets/${a.id}/test-resources`} method="post" className="stack"><div className="row"><input name="label" placeholder="Resource label" required/><input name="url" placeholder={`https://${a.normalizedHost}/api/test-resource/123`} required/><select name="method"><option value="GET">GET</option><option value="HEAD">HEAD</option></select></div><div className="row"><label>Owner <select name="ownerIdentityId">{a.testIdentities.map(i=><option key={i.id} value={i.id}>{i.label}</option>)}</select></label><select name="expectation"><option value="DENY_COMPARATORS">Deny selected comparators</option><option value="PUBLIC">Public</option></select><input name="proofMarker" placeholder="Optional harmless marker"/></div><div>{a.testIdentities.map(i=><label key={i.id} style={{marginRight:16}}><input type="checkbox" name="comparatorIdentityIds" value={i.id}/> {i.label}</label>)}</div><button className="btn">Add resource</button></form>}</div></>}
  </div>;
}
