CREATE TYPE "MemberRole" AS ENUM ('OWNER','ADMIN','MEMBER','VIEWER');
CREATE TYPE "VerificationMethod" AS ENUM ('DNS_TXT','FILE','META');
CREATE TYPE "VerificationStatus" AS ENUM ('PENDING','VERIFIED','FAILED','EXPIRED');
CREATE TYPE "ScanStatus" AS ENUM ('QUEUED','RUNNING','COMPLETED','FAILED','CANCELED');
CREATE TYPE "JobStatus" AS ENUM ('QUEUED','RUNNING','COMPLETED','FAILED','CANCELED');
CREATE TYPE "FindingStatus" AS ENUM ('OPEN','FIXED','IGNORED','FALSE_POSITIVE','RETESTING');
CREATE TYPE "Severity" AS ENUM ('CRITICAL','HIGH','MEDIUM','LOW','INFORMATIONAL');
CREATE TYPE "Confidence" AS ENUM ('CONFIRMED','HIGH','MEDIUM','LOW','NEEDS_REVIEW');

CREATE TABLE "User" ("id" UUID PRIMARY KEY, "email" TEXT NOT NULL UNIQUE, "passwordHash" TEXT NOT NULL, "name" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Organization" ("id" UUID PRIMARY KEY, "name" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "OrganizationMember" ("id" UUID PRIMARY KEY, "organizationId" UUID NOT NULL, "userId" UUID NOT NULL, "role" "MemberRole" NOT NULL DEFAULT 'MEMBER');
CREATE UNIQUE INDEX "OrganizationMember_organizationId_userId_key" ON "OrganizationMember"("organizationId","userId");
CREATE TABLE "Asset" ("id" UUID PRIMARY KEY, "organizationId" UUID NOT NULL, "name" TEXT NOT NULL, "baseUrl" TEXT NOT NULL, "normalizedHost" TEXT NOT NULL, "scanningEnabled" BOOLEAN NOT NULL DEFAULT true, "verifiedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX "Asset_organizationId_normalizedHost_key" ON "Asset"("organizationId","normalizedHost");
CREATE TABLE "AssetVerification" ("id" UUID PRIMARY KEY, "assetId" UUID NOT NULL, "method" "VerificationMethod" NOT NULL, "token" TEXT NOT NULL UNIQUE, "status" "VerificationStatus" NOT NULL DEFAULT 'PENDING', "failureReason" TEXT, "expiresAt" TIMESTAMP(3) NOT NULL, "verifiedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Scan" ("id" UUID PRIMARY KEY, "organizationId" UUID NOT NULL, "assetId" UUID NOT NULL, "status" "ScanStatus" NOT NULL DEFAULT 'QUEUED', "stage" TEXT NOT NULL DEFAULT 'Validation', "progress" INTEGER NOT NULL DEFAULT 0, "scope" JSONB NOT NULL, "cancelRequestedAt" TIMESTAMP(3), "startedAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "ScanJob" ("id" UUID PRIMARY KEY, "scanId" UUID NOT NULL, "queueJobId" TEXT UNIQUE, "status" "JobStatus" NOT NULL DEFAULT 'QUEUED', "attempt" INTEGER NOT NULL DEFAULT 0, "errorMessage" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "startedAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3));
CREATE TABLE "DiscoveredEndpoint" ("id" UUID PRIMARY KEY, "scanId" UUID NOT NULL, "url" TEXT NOT NULL, "method" TEXT NOT NULL, "parameters" JSONB, "responseCode" INTEGER, "contentType" TEXT, "external" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "DiscoveredEndpoint_scanId_url_idx" ON "DiscoveredEndpoint"("scanId","url");
CREATE TABLE "Finding" ("id" UUID PRIMARY KEY, "organizationId" UUID NOT NULL, "assetId" UUID NOT NULL, "scanId" UUID NOT NULL, "checkId" TEXT NOT NULL, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "category" TEXT NOT NULL, "severity" "Severity" NOT NULL, "confidence" "Confidence" NOT NULL, "status" "FindingStatus" NOT NULL DEFAULT 'OPEN', "affectedUrl" TEXT NOT NULL, "method" TEXT, "parameter" TEXT, "impact" TEXT NOT NULL, "remediation" TEXT NOT NULL, "fingerprint" TEXT NOT NULL, "firstSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE INDEX "Finding_organizationId_status_severity_idx" ON "Finding"("organizationId","status","severity");
CREATE INDEX "Finding_assetId_fingerprint_idx" ON "Finding"("assetId","fingerprint");
CREATE TABLE "FindingEvidence" ("id" UUID PRIMARY KEY, "findingId" UUID NOT NULL, "requestMethod" TEXT, "requestUrl" TEXT, "requestHeaders" JSONB, "requestBody" TEXT, "responseStatus" INTEGER, "responseHeaders" JSONB, "responseExcerpt" TEXT, "capturedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "FindingEvent" ("id" UUID PRIMARY KEY, "findingId" UUID NOT NULL, "type" TEXT NOT NULL, "message" TEXT, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "ScanLog" ("id" UUID PRIMARY KEY, "scanId" UUID NOT NULL, "level" TEXT NOT NULL, "stage" TEXT, "message" TEXT NOT NULL, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "ScanLog_scanId_createdAt_idx" ON "ScanLog"("scanId","createdAt");
CREATE TABLE "AuditLog" ("id" UUID PRIMARY KEY, "organizationId" UUID NOT NULL, "actorUserId" UUID, "action" TEXT NOT NULL, "targetType" TEXT NOT NULL, "targetId" TEXT, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "AuditLog_organizationId_createdAt_idx" ON "AuditLog"("organizationId","createdAt");

ALTER TABLE "OrganizationMember" ADD CONSTRAINT "OrganizationMember_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
ALTER TABLE "OrganizationMember" ADD CONSTRAINT "OrganizationMember_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Asset" ADD CONSTRAINT "Asset_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
ALTER TABLE "AssetVerification" ADD CONSTRAINT "AssetVerification_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "Asset"("id") ON DELETE CASCADE;
ALTER TABLE "Scan" ADD CONSTRAINT "Scan_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
ALTER TABLE "Scan" ADD CONSTRAINT "Scan_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "Asset"("id") ON DELETE CASCADE;
ALTER TABLE "ScanJob" ADD CONSTRAINT "ScanJob_scanId_fkey" FOREIGN KEY ("scanId") REFERENCES "Scan"("id") ON DELETE CASCADE;
ALTER TABLE "DiscoveredEndpoint" ADD CONSTRAINT "DiscoveredEndpoint_scanId_fkey" FOREIGN KEY ("scanId") REFERENCES "Scan"("id") ON DELETE CASCADE;
ALTER TABLE "Finding" ADD CONSTRAINT "Finding_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
ALTER TABLE "Finding" ADD CONSTRAINT "Finding_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "Asset"("id") ON DELETE CASCADE;
ALTER TABLE "Finding" ADD CONSTRAINT "Finding_scanId_fkey" FOREIGN KEY ("scanId") REFERENCES "Scan"("id") ON DELETE CASCADE;
ALTER TABLE "FindingEvidence" ADD CONSTRAINT "FindingEvidence_findingId_fkey" FOREIGN KEY ("findingId") REFERENCES "Finding"("id") ON DELETE CASCADE;
ALTER TABLE "FindingEvent" ADD CONSTRAINT "FindingEvent_findingId_fkey" FOREIGN KEY ("findingId") REFERENCES "Finding"("id") ON DELETE CASCADE;
ALTER TABLE "ScanLog" ADD CONSTRAINT "ScanLog_scanId_fkey" FOREIGN KEY ("scanId") REFERENCES "Scan"("id") ON DELETE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_actorUserId_fkey" FOREIGN KEY ("actorUserId") REFERENCES "User"("id") ON DELETE SET NULL;
